apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - synapse-config.yaml
  - synapse.yaml
  - element.yaml
  - certificates.yaml
  - httproute.yaml
