apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildkit
  namespace: actions
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-runner
  namespace: actions
automountServiceAccountToken: true
